name = "Meson"
grammar = "meson"
path_suffixes = ["build"]
line_comments = ["# "]
autoclose_before = ":.,=)}]"
tab_size = 2
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
